//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETS_database_structure.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ETS_database_structure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;/UML:Namespace.ownedElement&gt;
        ///            &lt;/UML:Model&gt;
        ///            &lt;UML:DataType name=&quot;string&quot; xmi.id=&quot;Dttp0&quot;/&gt;
        ///            &lt;UML:DataType name=&quot;int&quot; xmi.id=&quot;Dttp1&quot;/&gt;
        ///            &lt;UML:DataType name=&quot;datetime&quot; xmi.id=&quot;Dttp2&quot;/&gt;
        ///                   &lt;/XMI.content&gt;
        ///    &lt;/XMI&gt; 的本地化字符串。
        /// </summary>
        internal static string bottomtext {
            get {
                return ResourceManager.GetString("bottomtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&apos;1.0&apos; encoding=&apos;UTF-8&apos; ?&gt;
        ///    &lt;XMI xmlns:UML=&quot;//org.omg/UML/1.3&quot; xmi.version=&quot;1.1&quot;&gt;
        ///        &lt;XMI.header&gt;
        ///            &lt;XMI.documentation&gt;
        ///                &lt;XMI.exporter&gt;PowerDesigner&lt;/XMI.exporter&gt;
        ///            &lt;/XMI.documentation&gt;
        ///            &lt;XMI.metamodel xmi.name=&quot;UML&quot; xmi.version=&quot;1.3&quot;/&gt;
        ///        &lt;/XMI.header&gt;
        ///        &lt;XMI.content&gt;
        ///            &lt;UML:Model name=&quot;ObjectOrientedModel_3&quot; xmi.id=&quot;{03E79A51-09BF-45B6-B6B0-381B3C16B989}&quot;&gt;
        ///                &lt;UML:ModelElement.taggedValue&gt;
        ///     [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string headtext {
            get {
                return ResourceManager.GetString("headtext", resourceCulture);
            }
        }
    }
}
